apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: ecommerce-app
  labels:
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - image: chriscloudaz/ecommerceapp-k8s
        name: web-server
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: ecommerce-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31410
  selector:
    app: ecommerce-app
  type: NodePort

